spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
  datasource:
    username: minikowsky
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver